language: python
python:
  - 3.6
  - 3.7

before_install:
  - make build

branches:
  only:
    - master

install:
  - pip install -r requirements-develop.txt
  - python setup.py develop

script: 
  - make tests # run tests